//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper template tool. 
//---------------------------------------------------------------------------------------
using CqrsTemplatePack.Application.Features.Auth.Commands.Logout;
using CqrsTemplatePack.Application.Features.Auth.HttpClients;
using MediatR;

namespace CqrsTemplatePack.Application.Features.Auth.Handlers.Logout;

public class LogoutCommandHandler : INotificationHandler<LogoutCommand>
{
    IIdentityServerClientService _identityServerClientService;

    public LogoutCommandHandler(IIdentityServerClientService identityServerClientService)
    {
        _identityServerClientService = identityServerClientService;
    }

    public async Task Handle(LogoutCommand notification, CancellationToken cancellationToken)
    {
        await _identityServerClientService.RevokeRefreshToken(notification.RefreshToken);
    }
}
