//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper template tool. 
//---------------------------------------------------------------------------------------
using MediatR;

namespace CqrsTemplatePack.Application.Features.Auth.Commands.Logout;

public class LogoutCommand : INotification
{
    public string RefreshToken { get; set; }
}
