//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper template tool. 
//---------------------------------------------------------------------------------------
using Core.Persistence.Models.Responses;
using CqrsTemplatePack.Application.Features.Auth.Commands.Login;
using CqrsTemplatePack.Application.Features.Auth.Commands.RefreshToken;

namespace CqrsTemplatePack.Application.Features.Auth.HttpClients;

public interface IIdentityServerClientService
{
    Task<Response<LoginResponse>> CreateToken(LoginCommand request);

    Task<Response<RefreshTokenResponse>> RefreshToken(string refreshToken);

    Task<Response<NoContent>> RevokeRefreshToken(string refreshToken);
}
